global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['flask_app:8080']
  - job_name: 'flask_db_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['flask_db_exporter:9187']
